### ISSUE TITLE
Animate.css transitions has no callback and leads to bug with specific positions settings

### ISSUE THREAD

**Issue by hugohil** [soixantecircuits/piano#16]
For example:
Take an element with `data-position="top"` and piano initialized with `slideContent: true`.
When it appears, it goes on the top of the screen. When click out the keyboard container, the whole container slides down, but not behind visible part of the screen: it's still here, with its opacity to 0 but in the foreground so you can click on the keys and change the input.

**PRO TIP:**  answer's here: https://github.com/daneden/animate.css#usage

**Comment by kucherenkovova** [comment]
Fixed this with `display: none` in hide function and `display: block` in display function. The problem is caused by scaling keyboard.
