### ISSUE TITLE
demo doesn't work

### ISSUE THREAD

**Issue by rinaldi6109** [soixantecircuits/piano#33]
When I open the demo page http://soixantecircuits.github.io/piano/ and click inside some text box, nothing happens.
The console logs:
`Uncaught ReferenceError: Piano is not defined at HTMLDocument.<anonymous> (index.js:18)`

**Comment by gabrielstuff** [comment]
Nice found. Didn't know the demo page used to work. Going to check this. Thanks

**Comment by gabrielstuff** [comment]
hello @rinaldi6109 demo is fixed. Thanks for telling us.
