### ISSUE TITLE
The init param should always be an option object. The config, should always been an object.

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/piano#9]
I can see here : https://github.com/soixantecircuits/piano/blob/master/piano.js#L15 that the option is a `string`.

:no_entry:  Using string as an option is lame for several reason and has to be avoided : :no_entry: 

First, you never know if you might need more options.
Second, if you need more options, you'll have to rewrite a code to handle multiple option. This will also apply if you us an array instead of an object.
Third, it's easier to read in a separate file a option object than a string alone.

Thanks !

**Comment by Art2B** [comment]
https://github.com/soixantecircuits/piano/commit/251cdfffca2d9ac9d91ee9fd99c28707fdd6753b
